const products = [
   {
      id: 1,
      titulo:
         "Sistema HPLC de 6 piezas Agilent HP 1100 | Computadora de control",
      descripcion: "",
      imagen: "/assets/Productos/agilent-1100.jpg",
      configuracion: [
         "Bomba Isocrática G1310A.",
         "Detector de longitud de onda variable G1314A (VWD).",
         "Inyecto Manual G1328A.",
         "Software Chemstation B.04.03",
         "Bandeja de solventes.",
         "Todos los cables de alimentación y comunicación.",
      ],
      modulos: [
         "Muestreador automático G1313A o G1329A (ALS).",
         "Bomba binaria G1312A o cuaternaria G1311A.",
         "Detector de arreglo de diodos G1315A (DAD) o Detector de fluorescencia G1321A (FLD) o Detector de Índice de Refracción G1362A (RID) o Detector de longitud de onda múltiple G1365A (MWD).",
         "Compartimento de columna termostatizador G1316A.",
         "Módulo desgasificador G1322A o G1379A.",
      ],
      garantia: "6 meses",
   },
   {
      id: 2,
      titulo: "Sistema HPLC Agilent Technologies 1200 Series",
      descripcion: "",
      imagen: "/assets/Productos/agilent-1100.jpg",
      configuracion: [
         "Bomba Isocrática G1310B.",
         "Detector de longitud de onda variable G1314B (VWD).",
         "Inyecto Manual G1328A.",
         "Software Chemstation B.04.03",
         "Bandeja de solventes.",
         "Todos los cables de alimentación y comunicación.",
      ],
      modulos: [
         "Muestreador automático G1329B o G1367B (ALS).",
         "Bomba binaria G1312A o cuaternaria G1311A.",
         "Detector de arreglo de diodos G1315C (DAD) o Detector de fluorescencia G1321A (FLD) o Detector de Índice de Refracción G1362A (RID) o Detector de longitud de onda múltiple G1365B (MWD).",
         "Compartimento de columna termostatizador G1316A.",
         "Desgasificador G1322A o G1379A.",
      ],
      garantia: "6 meses",
   },
   {
      id: 3,
      titulo: "Sistema HPLC Agilent Technologies 1260 Infinity",
      descripcion: "",
      imagen: "/assets/Productos/1260-infinity.png",
      configuracion: [
         "Bomba Isocrática G1310B.",
         "Detector de longitud de onda variable G1314B (VWD).",
         "Inyecto Manual G1328A.",
         "Software Chemstation B.04.03",
         "Bandeja de solventes.",
         "Todos los cables de alimentación y comunicación.",
      ],
      modulos: [
         "Muestreador automático G1329B (ALS).",
         "Bomba binaria G1312B o cuaternaria G1311B.",
         "Detector de arreglo de diodos G1315C (DAD) o Detector de fluorescencia G1321B (FLD) o Detector de Índice de Refracción G1362A (RID) o Detector de longitud de onda múltiple G1365C (MWD).",
         "Compartimento de columna termostatizador G1316A.",
         "Desgasificador G1322B o G1379B.",
      ],
      garantia: "6 meses",
   },
   {
      id: 4,
      titulo: "Espectrofotómetro Hewlett Packard 8453",
      descripcion: "",
      imagen: "/assets/Productos/8453-hp.jpg",
      configuracion: [
         "Matriz de diodos que mide todo el espectro, desde la luz ultravioleta hasta la luz visible, y ofrece resultados en menos de un segundo.",
         "Sistema de espectrofotómetro de haz único sin partes móviles, lo que le proporciona una óptica estable, un alto rendimiento y un bajo nivel de ruido.",
         "Barrido de longitud de onda de 190-1100 nm y un ancho de rendija de 1 nm, lo que reduce la desviación de luz a < 0,03 %.",
      ],
      modulos: [],
      garantia: "6 meses",
   },
   {
      id: 5,
      titulo: "Sistema GC Agilent Technologies 6890N G1530N",
      descripcion: "",
      imagen: "/assets/Productos/6890n.jpg",
      configuracion: [
         "Con SSL único y FPD único.",
         "Muestreador automático Agilent (HP) 7683 Series: una torre de inyector G2913A, una bandeja G2914A.",
         "Cables de conexión y cables de alimentación.",
      ],
      modulos: [],
      garantia: "6 meses",
   },
   {
      id: 6,
      titulo: "Sistema GC Agilent Technologies 7890A",
      descripcion: "",
      imagen: "/assets/Productos/7890A.jpg",
      configuracion: [
         "Agilent 7890A Network Gas Chromatograph.",
         "Muestreador Automático Agilent 7683 Series.",
         "Single SSL Inlet and Single FID.",
         "Cables de conexión y cables de alimentación.",
      ],
      modulos: [],
      garantia: "6 meses",
   },
   {
      id: 7,
      titulo: "Muestreador Agilent 7697A Headspace",
      descripcion: "",
      imagen: "/assets/Productos/7697A.png",
      configuracion: [
         "Muestreador Agilent 7697A para cromatógrafo de gases y sistemas GCMS.",
         "Estándar 111 configuración de muestra con 3 muestras prioritarias.",
         "Bandejas intercambiables durante una secuencia para aumentar la capacidad de muestra.",
         "El portador de hidrógeno y los modos automáticos de reposo/activación conservan valiosos recursos de laboratorio.",
         "El control independiente de la presurización del vial y la presión del cabezal de la columna proporciona una mayor precisión al garantizar que no haya contrapresión durante la transferencia de muestras.",
      ],
      modulos: [],
      garantia: "6 meses",
   },
];

export default products;
